pub enum Lang {
    En,
    Zh,
    Ja,
}

pub struct Strings {
    pub app_title: &'static str,
    pub settings: &'static str,
    pub start: &'static str,
    pub clear: &'static str,
    pub remove: &'static str,
    pub add_files: &'static str,
    pub add_folder: &'static str,
    pub drop_hint: &'static str,
    pub col_file: &'static str,
    pub col_status: &'static str,
    pub status_pending: &'static str,
    pub status_processing: &'static str,
    pub status_skipped: &'static str,
    pub status_error: &'static str,
    pub preset_label: &'static str,
    pub format_label: &'static str,
    pub convert_only_label: &'static str,
    pub quality_label: &'static str,
    pub suffix_label: &'static str,
    pub output_dir_label: &'static str,
    pub threads_label: &'static str,
    pub overwrite_label: &'static str,
    pub log_mode_label: &'static str,
    pub width_label: &'static str,
    pub height_label: &'static str,
    pub bulk_add_title: &'static str,
    pub bulk_add_hint: &'static str,
    pub bulk_add_ok: &'static str,
    pub reset_defaults: &'static str,
    pub progress: &'static str,
    pub lang_label: &'static str,
}

pub fn strings(lang: &Lang) -> Strings {
    match lang {
        Lang::En => Strings {
            app_title: "CBZ Image Optimizer",
            settings: "Settings",
            start: "Start",
            clear: "Clear",
            remove: "Remove",
            add_files: "Add Files...",
            add_folder: "Add Folder...",
            drop_hint: "Drop ZIP/CBZ files or folders here",
            col_file: "File",
            col_status: "Status",
            status_pending: "− Pending",
            status_processing: "⏳ Processing...",
            status_skipped: "⚠ Skipped",
            status_error: "✗ Error",
            preset_label: "Preset",
            format_label: "Format",
            convert_only_label: "Convert only (no resize)",
            quality_label: "Quality",
            suffix_label: "Suffix",
            output_dir_label: "Output Dir",
            threads_label: "Threads",
            overwrite_label: "Overwrite",
            log_mode_label: "Log Mode",
            width_label: "Width",
            height_label: "Height",
            bulk_add_title: "Bulk Add Files",
            bulk_add_hint: "Enter full paths (one per line)",
            bulk_add_ok: "Add",
            reset_defaults: "Reset to defaults",
            progress: "{current}/{total} files",
            lang_label: "Language",
        },
        Lang::Zh => Strings {
            app_title: "CBZ 图像优化器",
            settings: "设置",
            start: "开始",
            clear: "清空",
            remove: "删除",
            add_files: "添加文件...",
            add_folder: "添加文件夹...",
            drop_hint: "将 ZIP/CBZ 文件或文件夹拖放到此处",
            col_file: "文件",
            col_status: "状态",
            status_pending: "− 待机",
            status_processing: "⏳ 处理中...",
            status_skipped: "⚠ 已跳过",
            status_error: "✗ 错误",
            preset_label: "预设",
            format_label: "格式",
            convert_only_label: "仅转换格式（不缩放）",
            quality_label: "质量",
            suffix_label: "后缀",
            output_dir_label: "输出目录",
            threads_label: "线程数",
            overwrite_label: "覆盖模式",
            log_mode_label: "日志模式",
            width_label: "宽度",
            height_label: "高度",
            bulk_add_title: "批量添加文件",
            bulk_add_hint: "输入完整路径（每行一个）",
            bulk_add_ok: "添加",
            reset_defaults: "恢复默认值",
            progress: "{current}/{total} 个文件",
            lang_label: "语言",
        },
        Lang::Ja => Strings {
            app_title: "CBZ 画像最適化ツール",
            settings: "設定",
            start: "開始",
            clear: "クリア",
            remove: "削除",
            add_files: "ファイル追加...",
            add_folder: "フォルダ追加...",
            drop_hint: "ZIP/CBZ ファイルまたはフォルダをここにドロップ",
            col_file: "ファイル",
            col_status: "ステータス",
            status_pending: "− 待機",
            status_processing: "⏳ 処理中...",
            status_skipped: "⚠ スキップ",
            status_error: "✗ エラー",
            preset_label: "プリセット",
            format_label: "フォーマット",
            convert_only_label: "フォーマット変換のみ（リサイズなし）",
            quality_label: "品質",
            suffix_label: "サフィックス",
            output_dir_label: "出力先",
            threads_label: "スレッド数",
            overwrite_label: "上書きモード",
            log_mode_label: "ログモード",
            width_label: "幅",
            height_label: "高さ",
            bulk_add_title: "一括ファイル登録",
            bulk_add_hint: "フルパスを1行ずつ入力",
            bulk_add_ok: "追加",
            reset_defaults: "デフォルトに戻す",
            progress: "{current}/{total} ファイル",
            lang_label: "言語",
        },
    }
}
