[package]
name = "cbz-tools-optimizer-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
avif-serialize.workspace = true
avif-parse.workspace = true
ravif.workspace = true
shiguredo_svt_av1.workspace = true
webp-anim.workspace = true
rayon.workspace = true
zip.workspace = true
unrar = { workspace = true, optional = true }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
clap = { version = "4", features = ["derive"], optional = true }

[features]
clap = ["dep:clap"]
rar = ["dep:unrar"]
